### ISSUE TITLE
Can not find icons

### ISSUE THREAD

**Issue by mateoreyes** [divio/djangocms-icon#23]
After update  Django 2.1.8 and Djangocms 3.6.0 I can't see de icons to chooose

![icon](https://user-images.githubusercontent.com/25666016/59276642-1aa9c600-8c35-11e9-917a-e982d71053a6.png)

**Comment by FinalAngel** [comment]
@mateoreyes what version of djangocms-icon do you use? How does your settings.py file look like in regards to the icons configurations.
