### ISSUE TITLE
Update (or document) for use with current Font Aweseome 5.0

### ISSUE THREAD

**Issue by FSE-DEV** [divio/djangocms-icon#8]
This is still targeted to work with old Font Aweseome 4.7.0. Would be great if this could be updated to be compatible with the current version of Font Awesome (5.0). Alternatively, a slightly more elaborate documentation would be helpful, e.g. with some hints on how to configure Font Awesome 5.0 as ones "own" SVG icon set.

Should I find the time to figure it out, I will follow up here.

Keep up the excellent work, team divio!

**Comment by FinalAngel** [comment]
Documentation added :)
