### ISSUE TITLE
Multiple iconsets cause problems with the icon selector widget

### ISSUE THREAD

**Issue by SteinRobert** [divio/djangocms-icon#9]
There is a problem with the icon selector widget using multiple icon sets.

Example:
```
DJANGOCMS_ICON_SETS = [
    (ICONSET, 'icon', 'SVG icons'),
    (ICONSET2, 'icon2', 'SVG icons 2'),
]
```

If one does select an icon from "SVG icons 2" and saves the plugin, opens it again, the wrong icon will be preselected (first of "SVG icons").
Steps to reproduce:

1. Use following configuration:
```
DJANGOCMS_ICON_SETS = [
    ('fontawesome', 'fa', 'Font Awesome'),
    (ICONSET, 'icon', 'SVG icons'),
]
```
2. Insert an icon plugin with an icon from "SVG Icons" into a placeholder.
3. Open the plugin again - wrong icon will be selected.

**Comment by vxsx** [comment]
https://github.com/divio/djangocms-icon/commit/3fb2c1a0946349c0d04f7ef8f0d315b652160a65 should've fixed this problem

any chance you are using it on Divio Cloud? if that's the case and the addon was upgraded - please make sure that the static files and template are removed from the project.

i will try to reproduce in the meantime

**Comment by SteinRobert** [comment]
I'm using version 1.0.0. Let me know if you cannot reproduce the issue.

**Comment by vxsx** [comment]
I can reproduce the problem with 2 svg iconsets, thanks, looking into this

**Comment by vxsx** [comment]
It looks like the field renderer tries to infer the iconset out of the icon name:

https://github.com/divio/djangocms-icon/blob/dd8abebd32ffb94e001dd3028e8f01b5fd84cb8d/djangocms_icon/fields.py#L31-L37

Meaning that if value is `icon-something` it would think that the prefix is `icon`. So it would select the iconset based on that. And in case the iconset prefix doesn't match the one in settings it would always pick the first one no matter what. This is likely what leads to the bug you're experiencing

**Comment by SteinRobert** [comment]
I can confirm this. Changing the prefix in my second symbol-def SVG file make the whole thing work.
